import { nanoid } from "nanoid";

export default [
    {
        productName: "Colombia Supremo",
        img: "/images/product2.jpg",
        roastType: "Medium Roast",
        price: 175,
        productType: "Classic Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Smooth Highlands",
        img: "/images/product2.jpg",
        roastType: "Dark Roast",
        price: 145,
        productType: "Classic Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Homeland Barako",
        img: "/images/product3.jpg",
        roastType: "Dark Roast",
        price: 125,
        productType: "Classic Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Brazil Santos",
        img: "/images/product4.jpg",
        roastType: "Medium Roast",
        price: 0,
        productType: "Classic Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Vintage Earth",
        img: "/images/product5.jpg",
        roastType: "Dark Roast",
        price: 120,
        productType: "Classic Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Sagada Arabica",
        img: "/images/product6.jpg",
        roastType: "Dark Roast",
        price: 150,
        productType: "Classic Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Ethiopia Yirgacheffe",
        img: "/images/product7.jpg",
        roastType: "Medium Roast",
        price: 175,
        productType: "Classic Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Vibrant Hazelnut",
        img: "/images/coffee1.png",
        roastType: "Medium Roast",
        price: 135,
        productType: "Flavored Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Floral Vanilla",
        img: "/images/coffee2.png",
        roastType: "Medium Dark Roast",
        price: 135,
        productType: "Flavored Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Tropical Summer",
        img: "/images/coffee5.png",
        roastType: "Dark Roast",
        price: 135,
        productType: "Flavored Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Bronzed Caramel",
        img: "/images/product7.jpg",
        roastType: "Medium Dark Roast",
        price: 175,
        productType: "Flavored Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Java Mocha",
        img: "/images/product7.jpg",
        roastType: "Medium Dark Roast",
        price: 175,
        productType: "Flavored Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
    {
        productName: "Bright Butterscotch",
        img: "images/product7.jpg",
        roastType: "Medium Dark Roast",
        price: 175,
        productType: "Flavored Coffee Beans",
        productId: nanoid(),
        isAddedtoCart: false,
    },
];
